[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
fs_permissions = [{ access = "read", path = "./broadcast" }]
solc = "0.8.19"
# Config reviewed Dec 2025 to confirm RPC/remapping entries remain accurate.

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
zksync-local = "http://127.0.0.1:8011"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
